ARG ES_VERSION=${ES_VERSION}

# FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
FROM registry.cn-hangzhou.aliyuncs.com/elasticsearch/aliyun-elasticsearch

VOLUME ["/data"]

EXPOSE 9200 9300